---
title: "Multi-region sampling"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Multi-region sampling}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, setup-hidden}
#| include: false
knitr::opts_chunk$set(fig.alt = " ")
knitr::opts_chunk$set(collapse = TRUE)
```

## Workflow

Perform simulation and extract population data:

```{r prepare}
library(ggplot2)
library(tumopp)
set.seed(24601L)
result = tumopp::tumopp("-N20000 -D3 -Chex -Lconst -k10")
population = result$population[[1L]]
graph = result$graph[[1L]]
```

Sample cells and put neutral mutations on the lineages:

```{r sample}
extant = population |> tumopp::filter_extant()
ncell = 200L
regions = tumopp::sample_uniform_regions(extant, nsam = 4L, ncell = ncell)
subgraph = tumopp::subtree(graph, unlist(regions$id))
vaf = tumopp::make_vaf(subgraph, regions$id, mu = 8.0) |> print()
```

Estimate $F_{ST}$ from VAF.

```{r fst}
tumopp::dist_vaf(vaf, ncell) |> tumopp::fst()

# True FST from cell genealogy
tumopp::dist_genealogy(subgraph, regions$id) |> tumopp::fst()
```

Summarize and visualize VAF:

```{r visualize}
#| eval: false
vaf_tidy = vaf |>
  tumopp::filter_detectable(0.01) |>
  tumopp::sort_vaf() |>
  tumopp::longer_vaf() |>
  print()

ggplot(vaf_tidy) +
  aes(sample, site) +
  geom_tile(aes(fill = frequency)) +
  scale_fill_distiller(palette = "Spectral", limit = c(0, 1), guide = FALSE) +
  coord_cartesian(expand = FALSE)
```
