---
title: "Introduction to tumopp"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to tumopp}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(dplyr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Basic usage

This is an R interface of [tumopp](https://github.com/heavywatal/tumopp),
a tumor growth simulator in C++.
The parameter values and resulting populations are returned in a nested [tibble](https://tibble.tidyverse.org/).
See `?tumopp` for details.

```{r run}
library(tumopp)
result = tumopp("--seed=24601 -D3 -Cmoore -k10 -N1000")
colnames(result)
result$population[[1L]] |> dplyr::arrange(id)
```

## Explore parameter space

A parameter grid can be generated with `make_args()`.
See `tumopp("--help")` or
[C++ library documentation generated by doxygen](https://heavywatal.github.io/tumopp/group__params.html)
for available parameters.

```{r make_args}
.const = list(D = 3L, C = "hex", N = 1000L)
.alt = list(
  k = c("1", "1e6"),
  L = c("const", "linear", "step"),
  P = c("random", "mindrag")
)

# Generate combinations of arguments
args_table = make_args(alt = .alt, const = .const, each = 1L)
args_table |> dplyr::select(-o)

# Concurrent execution
results = tumopp(args_table)
results |>
  dplyr::select(-outdir, -seed, -where(is.list)) |>
  dplyr::select(where(\(x) dplyr::n_distinct(x) > 1L))
```
