# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run C++ simulation
#' @param args command line arguments as a string vector
#' @rdname rcpprun
cpp_tumopp <- function(args) {
    .Call(`_tumopp_cpp_tumopp`, args)
}

