# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run C++ simulation
#' @param args command line arguments as a string vector or list of strings
#' @param npair number of samples to measure genetic and physical distance
#' @rdname rcpprun
cpp_tumopp <- function(args, npair = 0L) {
    .Call('_tumopp_cpp_tumopp', PACKAGE = 'tumopp', args, npair)
}

#' @param nsam number of samples for ms-like output
#' @rdname rcpprun
cpp_tumopp_ms <- function(nsam, args) {
    .Call('_tumopp_cpp_tumopp_ms', PACKAGE = 'tumopp', nsam, args)
}

